services:

  # API Gateway
  gateway:
    extends:
      file: ./gateway/compose.yaml
      service: gateway
    build: ./gateway/

  # users-identity
  users-identity-service:
    extends:
      file: ./user-identity-be/compose.yaml
      service: users-identity-service
    build: ./user-identity-be/
    depends_on:
      - users-identity-service-db

  users-identity-service-db:
    extends:
      file: ./user-identity-be/compose.yaml
      service: users-identity-service-db

  # events
  be-events-service:
    extends:
      file: ./be-events/docker-compose.yml
      service: be-events-service
    build: ./be-events/
    depends_on:
      - be-events-service-db

  be-events-service-db:
    extends:
      file: ./be-events/docker-compose.yml
      service: be-events-service-db

  # payments
  payments:
    extends:
      file: ./payments-be/compose.yaml
      service: payments
    build: ./payments-be/
    depends_on:
      - payments-db

  payments-db:
    extends:
      file: ./payments-be/compose.yaml
      service: payments-db
