services:
  
  # API Gateway
  gateway:
    extends:
      file: ./gateway/compose.yaml
      service: gateway
    build: ./gateway/

  users-identity-service:
    extends:
      file: ./user-identity-be/compose.yaml
      service: users-identity-service
    build: ./user-identity-be/
    depends_on:
      - users-identity-service-db

  be-events-service:
    extends:
      file: ./be-events/docker-compose.yml
      service: be-events-service
    build: ./be-events/

  users-identity-service-db:
    extends: 
      file: ./user-identity-be/compose.yaml
      service: users-identity-service-db
