services:
  payments:
    image: larpex/payments:latest
    ports:
      - "8087:8080"
    build: .

  payments-db:
    image: postgres:latest
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payments
    ports:
      - 5436:5432
