springdoc:
  swagger-ui:
    url: "/openapi.yaml"

spring:
  cloud:
    gateway:
      routes:
        - id: users
          uri: http://users-identity-service:8080
          predicates:
            - Path=/users/**
        - id: events
          uri: http://be-events-service:8083
          predicates:
            - Path=/events/**
