services:
  usersdb:
    image: postgres:latest
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db:/users-entrypoint-initdb.d/
    ports:
      - 5435:5432
  usersliquibase:
    image: liquibase/liquibase:latest
    volumes:
      - ./liquibase:/liquibase/changelog
    command: liquibase --url="jdbc:postgresql://usersdb:5432/users" --changeLogFile=changelog/changelog.xml --username=root --password=password update
    depends_on:
      - usersdb
