FROM node:18-alpine3.16
RUN apk update && apk add --no-cache openssl
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json", "./"]
COPY prisma ./prisma/
RUN npm install
RUN npx prisma generate
COPY . .
CMD npx prisma db push && npx prisma db seed && npm run dev & npx prisma studio --port ${BE_EVENTS___PRISMA_STUDIO_PORT}