services:
  paymentsdb:
    image: postgres:latest
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payments
    volumes:
      - ./db:/payments-entrypoint-initdb.d/
    ports:
      - 5434:5432
  paymentsliquibase:
    image: liquibase/liquibase:latest
    volumes:
      - ./liquibase:/liquibase/changelog
    command: liquibase --url="jdbc:postgresql://paymentsdb:5432/payments" --changeLogFile=changelog/changelog.xml --username=root --password=password update
    depends_on:
      - paymentsdb
