spring:
  datasource:
    url: jdbc:postgresql://users-identity-service-db:5432/users
    username: root
    password: password
  liquibase:
    change-log: db/changelog/changelog-master.xml
    contexts: "no-context" # This is just so that liquibase does not include every changeset
