name: Build payments service backend

on:
  push:
    branches: ["main"]
    paths:
      - "payments-be/**"
  pull_request:
    branches: ["main"]
    paths:
      - "payments-be/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      working-directory: payments-be

    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package
