name: Build user identity service backend

on:
  push:
    branches: ["master"]
    paths:
      - "user-identity-be/**"
  pull_request:
    branches: ["master"]
    paths:
      - "user-identity-be/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      working-directory: user-identity-be

    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Set up gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew build
